### ISSUE TITLE
Why is this not a Fork?

### ISSUE THREAD

**Issue by MainframeVRC** [PlagueVRC/AntiRip#1]
Since it was [GTAvaCrypt](https://github.com/rygo6/GTAvaCrypt) why didn't you fork it?  
That's not very OSS of you  

Also calling it AntiRip is misleading as it only increases the difficulty to rip

**Comment by MistressPlague** [comment]
Because not only is GTAvaCrypt discontinued, but I was a co-developer of the original, and was told by ryan personally to rebrand this away from his LLC.

Furthermore, this is a anti rip. It is a ripping protection system ranging in technologies, and has elements making it borderline impossible to rip in the end-result.

Why do you put out false claims without purpose? What is your goal here other than to ruin other people's days?

**Comment by MistressPlague** [comment]
Quite amusing you made this burner account just to ruin others' days instead of actually linking your words to your alias. You don't even deserve attention for having that much insecurity.
